services:
  qtim:
    build:
      context: .
      dockerfile: "./Dockerfile"
    ports:
      - "3000:3000"
    volumes:
      - .:/qtim
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${SQLUSER}
      - POSTGRES_PASSWORD=${SQLPASSWORD}
      - POSTGRES_DB=${SQLDATABASE}
    expose:
      - ${SQLPORT}
    volumes: 
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: